export const GAME_EVENTS = Object.freeze({
  ACTION_REGISTERED: "ACTION_REGISTERED",
  XP_GAINED: "XP_GAINED",
  LEVEL_UP: "LEVEL_UP",

  MISSION_PROGRESS: "MISSION_PROGRESS",
  MISSION_COMPLETED: "MISSION_COMPLETED",

  ACHIEVEMENT_UNLOCKED: "ACHIEVEMENT_UNLOCKED",

  RANK_CHANGED: "RANK_CHANGED",
  STREAK_UPDATED: "STREAK_UPDATED",

  NOTIFICATION_CREATED: "NOTIFICATION_CREATED",
});