-- BarberXP v84: catálogo, estoque e comissão por função.
-- Execute em uma consulta nova. Não apaga dados nem calcula comissão retroativa.
begin;

create table if not exists public.product_commission_rules (
  id integer primary key default 1 check (id=1),
  barber_percent numeric(5,2) not null default 15 check (barber_percent between 0 and 100),
  reception_percent numeric(5,2) not null default 10 check (reception_percent between 0 and 100),
  updated_at timestamptz not null default now()
);
insert into public.product_commission_rules(id) values(1) on conflict do nothing;
alter table public.product_commission_rules enable row level security;
drop policy if exists product_commission_read on public.product_commission_rules;
create policy product_commission_read on public.product_commission_rules for select to authenticated
using (exists(select 1 from public.profiles where id=auth.uid() and active));
grant select on public.product_commission_rules to authenticated;
revoke insert,update,delete on public.product_commission_rules from authenticated,anon;

create table if not exists public.product_stock_entries (
  id bigint generated by default as identity primary key,
  product_id bigint not null references public.products(id) on delete cascade,
  quantity integer not null check (quantity>0),
  note text,
  created_by uuid not null references public.profiles(id),
  created_at timestamptz not null default now()
);
alter table public.product_stock_entries add column if not exists unit_cost numeric(12,2);
alter table public.product_stock_entries enable row level security;
drop policy if exists product_stock_entries_owner_read on public.product_stock_entries;
create policy product_stock_entries_owner_read on public.product_stock_entries for select to authenticated
using (exists(select 1 from public.profiles where id=auth.uid() and active and role in ('leader','manager')));
drop policy if exists product_stock_entries_owner_insert on public.product_stock_entries;
create policy product_stock_entries_owner_insert on public.product_stock_entries for insert to authenticated
with check (created_by=auth.uid() and exists(select 1 from public.profiles where id=auth.uid() and active and role in ('leader','manager')));
grant select,insert on public.product_stock_entries to authenticated;
grant usage,select on sequence public.product_stock_entries_id_seq to authenticated;

create or replace function public.product_stock_cost_v84()
returns trigger language plpgsql security definer set search_path=public,pg_temp as $$
begin
  select round(cost_price::numeric,2) into new.unit_cost from public.products where id=new.product_id;
  return new;
end; $$;
drop trigger if exists product_stock_cost_v84 on public.product_stock_entries;
create trigger product_stock_cost_v84 before insert on public.product_stock_entries
for each row execute function public.product_stock_cost_v84();

-- Os valores vêm do catálogo e da função real do vendedor, nunca do celular.
create or replace function public.product_sale_snapshot_v84()
returns trigger language plpgsql security definer set search_path=public,pg_temp as $$
declare
  v_product public.products%rowtype;
  v_role text;
  v_percent numeric;
  v_sale numeric;
  v_cost numeric;
  v_commission numeric;
  v_customer_type text;
  v_list_price numeric;
  v_discount_percent numeric;
begin
  if tg_op='UPDATE' then
    if old.metadata->>'financial_version'='84' then
      if new.action_key is distinct from old.action_key or new.user_id is distinct from old.user_id then
        raise exception 'Não altere o vendedor ou tipo de uma venda registrada.';
      end if;
      new.metadata := coalesce(new.metadata,'{}'::jsonb) || jsonb_build_object(
        'product_id',old.metadata->'product_id','product_name',old.metadata->'product_name',
        'sale_price',old.metadata->'sale_price','cost_price',old.metadata->'cost_price',
        'commission_percent',old.metadata->'commission_percent','commission_amount',old.metadata->'commission_amount',
        'seller_role',old.metadata->'seller_role','profit',old.metadata->'profit',
        'customer_type',old.metadata->'customer_type','list_price',old.metadata->'list_price',
        'discount_percent',old.metadata->'discount_percent','discount_amount',old.metadata->'discount_amount',
        'financial_version',84,'financial_recorded_at',old.metadata->'financial_recorded_at');
    else
      -- Uma venda antiga não recebe comissão retroativa por edição de metadata.
      new.metadata := coalesce(new.metadata,'{}'::jsonb) - 'financial_version' - 'commission_percent' - 'commission_amount' - 'financial_recorded_at';
    end if;
    return new;
  end if;
  if new.action_key<>'produtos' then return new; end if;
  if auth.uid() is not null and auth.uid()<>new.user_id then raise exception 'Registre a venda na conta do vendedor.'; end if;
  select role into v_role from public.profiles where id=new.user_id and active;
  if not found then raise exception 'Vendedor não está ativo.'; end if;
  if coalesce(new.metadata->>'product_id','') !~ '^[0-9]+$' then raise exception 'Selecione um produto do catálogo.'; end if;
  select * into v_product from public.products where id=(new.metadata->>'product_id')::bigint and active;
  if not found then raise exception 'Produto não está disponível no catálogo.'; end if;
  select case when v_role='manager' then reception_percent else barber_percent end into v_percent
  from public.product_commission_rules where id=1;
  v_customer_type := new.metadata->>'customer_type';
  if v_customer_type is null or v_customer_type not in ('regular','subscriber') then
    raise exception 'Informe se o cliente tem plano ou não. Atualize o aplicativo se a opção não aparecer.';
  end if;
  v_list_price := round(v_product.sale_price::numeric,2);
  v_discount_percent := case when v_customer_type='subscriber' then 10 else 0 end;
  v_sale := round(v_list_price*(100-v_discount_percent)/100,2);
  v_cost := round(v_product.cost_price::numeric,2);
  if v_sale is null or v_cost is null or v_sale<0 or v_cost<0 then raise exception 'Confira o preço e custo do produto.'; end if;
  v_commission := round(v_sale*v_percent/100,2);
  new.metadata := coalesce(new.metadata,'{}'::jsonb) || jsonb_build_object(
    'product_id',v_product.id,'product_name',v_product.name,'sale_price',v_sale,'cost_price',v_cost,
    'seller_role',v_role,'commission_percent',v_percent,'commission_amount',v_commission,
    'customer_type',v_customer_type,'list_price',v_list_price,'discount_percent',v_discount_percent,'discount_amount',v_list_price-v_sale,
    'profit',v_sale-v_cost-v_commission,'financial_version',84,'financial_recorded_at',now());
  return new;
end; $$;
drop trigger if exists product_sale_snapshot_v84 on public.barber_actions;
create trigger product_sale_snapshot_v84 before insert or update on public.barber_actions
for each row execute function public.product_sale_snapshot_v84();

create or replace function public.save_product_catalog_v84(p_products jsonb,p_barber_percent numeric,p_reception_percent numeric,p_profit_goal numeric)
returns jsonb language plpgsql security definer set search_path=public,pg_temp as $$
declare
  v_item jsonb;
  v_id bigint;
  v_kept bigint[] := '{}';
  v_name text;
  v_sale numeric;
  v_cost numeric;
  v_owner boolean;
begin
  if not exists(select 1 from public.profiles where id=auth.uid() and active and role in ('leader','manager')) then
    raise exception 'Somente o dono ou gestor pode salvar o catálogo.';
  end if;
  select role='leader' into v_owner from public.profiles where id=auth.uid();
  if p_products is null or jsonb_typeof(p_products)<>'array' then raise exception 'Catálogo inválido.'; end if;
  if p_barber_percent is null or p_reception_percent is null or p_profit_goal is null
     or p_barber_percent not between 0 and 100 or p_reception_percent not between 0 and 100
     or p_profit_goal<0 or p_profit_goal::text in ('NaN','Infinity','-Infinity') then
    raise exception 'Confira as comissões (0 a 100) e a meta.';
  end if;
  if v_owner then
    update public.product_commission_rules set barber_percent=round(p_barber_percent,2),
      reception_percent=round(p_reception_percent,2),updated_at=now() where id=1;
  end if;
  for v_item in select value from jsonb_array_elements(p_products) loop
    v_id := nullif(v_item->>'id','')::bigint;
    v_name := btrim(v_item->>'name');
    v_sale := (v_item->>'sale_price')::numeric;
    v_cost := (v_item->>'cost_price')::numeric;
    if v_name is null or v_name='' or char_length(v_name)>120 or v_sale is null or v_cost is null
       or v_sale<0 or v_cost<0 or v_sale::text in ('NaN','Infinity','-Infinity')
       or v_cost::text in ('NaN','Infinity','-Infinity') then raise exception 'Confira nome, preço e custo de todos os produtos.'; end if;
    if v_id is null then
      insert into public.products(name,sale_price,cost_price,active,created_by,updated_at)
      values(v_name,round(v_sale,2),round(v_cost,2),true,auth.uid(),now()) returning id into v_id;
    else
      if v_id=any(v_kept) then raise exception 'Produto repetido no catálogo.'; end if;
      update public.products set name=v_name,sale_price=round(v_sale,2),cost_price=round(v_cost,2),active=true,updated_at=now() where id=v_id;
      if not found then raise exception 'Produto não encontrado. Atualize o catálogo.'; end if;
    end if;
    v_kept := array_append(v_kept,v_id);
  end loop;
  update public.products set active=false,updated_at=now() where active and not(id=any(v_kept));
  if v_owner then
    update public.game_strategy set monthly_product_profit_goal=round(p_profit_goal,2),updated_by=auth.uid(),updated_at=now() where id=1;
  end if;
  return jsonb_build_object('products',(select coalesce(jsonb_agg(p order by p.name),'[]'::jsonb) from public.products p where active),
    'rules',(select to_jsonb(r) from public.product_commission_rules r where id=1));
end; $$;
revoke all on function public.save_product_catalog_v84(jsonb,numeric,numeric,numeric) from public,anon;
grant execute on function public.save_product_catalog_v84(jsonb,numeric,numeric,numeric) to authenticated;
notify pgrst,'reload schema';
commit;
