-- BarberXP v41: central de notificações e sincronização em tempo real

create table if not exists public.app_notifications (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  type text not null default 'general',
  title text not null,
  message text not null,
  metadata jsonb not null default '{}'::jsonb,
  created_by uuid references public.profiles(id) on delete set null,
  created_at timestamptz not null default now(),
  read_at timestamptz
);

create index if not exists app_notifications_user_created_idx
  on public.app_notifications (user_id, created_at desc);

alter table public.app_notifications enable row level security;

drop policy if exists "notifications_read_own" on public.app_notifications;
create policy "notifications_read_own"
on public.app_notifications for select to authenticated
using (user_id = auth.uid());

drop policy if exists "notifications_update_own" on public.app_notifications;
create policy "notifications_update_own"
on public.app_notifications for update to authenticated
using (user_id = auth.uid())
with check (user_id = auth.uid());

drop policy if exists "notifications_create_team" on public.app_notifications;
create policy "notifications_create_team"
on public.app_notifications for insert to authenticated
with check (created_by = auth.uid());

do $$
begin
  alter publication supabase_realtime add table public.app_notifications;
exception
  when duplicate_object then null;
end $$;

grant select, insert, update on public.app_notifications to authenticated;
grant usage, select on sequence public.app_notifications_id_seq to authenticated;

notify pgrst, 'reload schema';
