-- BarberXP v49 — metas adaptativas, produtos e evolução semanal

alter table public.barber_actions
  add column if not exists metadata jsonb not null default '{}'::jsonb;
alter table public.barber_actions
  add column if not exists review_reason text;

create table if not exists public.game_strategy (
  id smallint primary key default 1 check (id = 1),
  focus_mode text not null default 'auto' check (focus_mode in ('auto','produtos','extras','assinaturas')),
  monthly_product_profit_goal numeric(12,2) not null default 1000 check (monthly_product_profit_goal >= 0),
  weekly_bonus_easy integer not null default 3 check (weekly_bonus_easy >= 0),
  weekly_bonus_medium integer not null default 4 check (weekly_bonus_medium >= 0),
  weekly_bonus_hard integer not null default 5 check (weekly_bonus_hard >= 0),
  updated_by uuid references public.profiles(id),
  updated_at timestamptz not null default now()
);

insert into public.game_strategy(id) values (1) on conflict (id) do nothing;

create table if not exists public.member_game_settings (
  user_id uuid primary key references public.profiles(id) on delete cascade,
  development boolean not null default false,
  joined_at date,
  updated_by uuid references public.profiles(id),
  updated_at timestamptz not null default now()
);

create table if not exists public.products (
  id bigint generated by default as identity primary key,
  name text not null,
  sale_price numeric(12,2) not null default 0 check (sale_price >= 0),
  cost_price numeric(12,2) not null default 0 check (cost_price >= 0),
  active boolean not null default true,
  created_by uuid references public.profiles(id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.weekly_challenges (
  id bigint generated by default as identity primary key,
  week_start date not null,
  user_id uuid not null references public.profiles(id) on delete cascade,
  focus_key text not null check (focus_key in ('produtos','extras','assinaturas')),
  easy_target integer not null check (easy_target > 0),
  medium_target integer not null check (medium_target >= easy_target),
  hard_target integer not null check (hard_target >= medium_target),
  progress integer not null default 0 check (progress >= 0),
  bonus_awarded integer not null default 0 check (bonus_awarded >= 0),
  development boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (week_start,user_id)
);

alter table public.game_strategy enable row level security;
alter table public.member_game_settings enable row level security;
alter table public.products enable row level security;
alter table public.weekly_challenges enable row level security;

drop policy if exists game_strategy_read on public.game_strategy;
create policy game_strategy_read on public.game_strategy for select to authenticated using (true);
drop policy if exists game_strategy_owner on public.game_strategy;
create policy game_strategy_owner on public.game_strategy for all to authenticated
using (exists(select 1 from public.profiles p where p.id=auth.uid() and p.role='leader'))
with check (exists(select 1 from public.profiles p where p.id=auth.uid() and p.role='leader'));

drop policy if exists member_game_read on public.member_game_settings;
create policy member_game_read on public.member_game_settings for select to authenticated using (true);
drop policy if exists member_game_owner on public.member_game_settings;
create policy member_game_owner on public.member_game_settings for all to authenticated
using (exists(select 1 from public.profiles p where p.id=auth.uid() and p.role='leader'))
with check (exists(select 1 from public.profiles p where p.id=auth.uid() and p.role='leader'));

drop policy if exists products_read on public.products;
create policy products_read on public.products for select to authenticated using (true);
drop policy if exists products_owner on public.products;
create policy products_owner on public.products for all to authenticated
using (exists(select 1 from public.profiles p where p.id=auth.uid() and p.role='leader'))
with check (exists(select 1 from public.profiles p where p.id=auth.uid() and p.role='leader'));

drop policy if exists weekly_challenges_read on public.weekly_challenges;
create policy weekly_challenges_read on public.weekly_challenges for select to authenticated using (true);

grant select on public.game_strategy,public.member_game_settings,public.products,public.weekly_challenges to authenticated;
grant insert,update,delete on public.game_strategy,public.member_game_settings,public.products to authenticated;
grant usage,select on all sequences in schema public to authenticated;

create or replace function public.barberxp_week_start()
returns date language sql stable as $$
  select ((now() at time zone 'America/Sao_Paulo')::date
    - (extract(isodow from now() at time zone 'America/Sao_Paulo')::integer - 1));
$$;

create or replace function public.ensure_current_weekly_challenges()
returns void language plpgsql security definer set search_path=public as $$
declare
  v_week date := public.barberxp_week_start();
  v_mode text;
  v_focus text;
  v_member record;
  v_avg numeric;
  v_easy integer;
  v_medium integer;
  v_hard integer;
  v_progress integer;
begin
  select focus_mode into v_mode from public.game_strategy where id=1;
  v_mode := coalesce(v_mode,'auto');
  if v_mode <> 'auto' then v_focus := v_mode;
  else
    v_focus := case (extract(week from v_week)::integer % 4)
      when 0 then 'produtos' when 1 then 'extras'
      when 2 then 'produtos' else 'assinaturas' end;
  end if;

  for v_member in
    select p.id,coalesce(m.development,false) development
    from public.profiles p left join public.member_game_settings m on m.user_id=p.id
    where p.active=true and p.role in ('leader','barber')
  loop
    select count(*)::numeric/4 into v_avg
    from public.barber_actions a
    where a.user_id=v_member.id and a.status='approved' and a.action_key=v_focus
      and a.created_at >= (v_week-28)::timestamptz and a.created_at < v_week::timestamptz;
    v_avg := coalesce(v_avg,0);
    if v_focus='extras' then
      v_easy:=greatest(2,ceil(v_avg*(case when v_member.development then .65 else .85 end))::int);
      v_medium:=greatest(v_easy+1,ceil(v_avg*(case when v_member.development then .9 else 1.10 end))::int);
      v_hard:=greatest(v_medium+1,ceil(v_avg*(case when v_member.development then 1.15 else 1.40 end))::int);
    elsif v_focus='produtos' then
      v_easy:=greatest(1,ceil(v_avg*(case when v_member.development then .65 else .85 end))::int);
      v_medium:=greatest(v_easy+1,ceil(v_avg*(case when v_member.development then .9 else 1.10 end))::int);
      v_hard:=greatest(v_medium+1,ceil(v_avg*(case when v_member.development then 1.15 else 1.40 end))::int);
    else
      v_easy:=greatest(1,ceil(v_avg*.8)::int);
      v_medium:=greatest(v_easy,ceil(v_avg*1.10)::int);
      v_hard:=greatest(v_medium+1,ceil(v_avg*1.40)::int);
    end if;
    select count(*) into v_progress from public.barber_actions a
      where a.user_id=v_member.id and a.status='approved' and a.action_key=v_focus
        and (a.created_at at time zone 'America/Sao_Paulo')::date between v_week and v_week+6;
    insert into public.weekly_challenges(week_start,user_id,focus_key,easy_target,medium_target,hard_target,progress,development)
      values(v_week,v_member.id,v_focus,v_easy,v_medium,v_hard,v_progress,v_member.development)
    on conflict(week_start,user_id) do nothing;
  end loop;
end $$;

create or replace function public.apply_weekly_challenge(p_action_id bigint)
returns jsonb language plpgsql security definer set search_path=public as $$
declare
  v_action public.barber_actions%rowtype;
  v_goal public.weekly_challenges%rowtype;
  v_strategy public.game_strategy%rowtype;
  v_progress integer;
  v_total integer:=0;
  v_delta integer:=0;
  v_state jsonb;
begin
  select * into v_action from public.barber_actions where id=p_action_id and status='approved';
  if not found then return jsonb_build_object('ok',false,'code','action_not_approved'); end if;
  perform public.ensure_current_weekly_challenges();
  select * into v_goal from public.weekly_challenges
    where user_id=v_action.user_id and week_start<=((v_action.created_at at time zone 'America/Sao_Paulo')::date)
      and week_start+6>=((v_action.created_at at time zone 'America/Sao_Paulo')::date) for update;
  if not found or v_goal.focus_key<>v_action.action_key then return jsonb_build_object('ok',true,'bonus',0); end if;
  select * into v_strategy from public.game_strategy where id=1;
  select count(*) into v_progress from public.barber_actions a
    where a.user_id=v_goal.user_id and a.status='approved' and a.action_key=v_goal.focus_key
      and (a.created_at at time zone 'America/Sao_Paulo')::date between v_goal.week_start and v_goal.week_start+6;
  if v_progress>=v_goal.easy_target then v_total:=v_total+v_strategy.weekly_bonus_easy; end if;
  if v_progress>=v_goal.medium_target then v_total:=v_total+v_strategy.weekly_bonus_medium; end if;
  if v_progress>=v_goal.hard_target then v_total:=v_total+v_strategy.weekly_bonus_hard; end if;
  v_delta:=greatest(0,v_total-v_goal.bonus_awarded);
  update public.weekly_challenges set progress=v_progress,bonus_awarded=v_total,updated_at=now() where id=v_goal.id;
  if v_delta>0 then
    select state into v_state from public.barber_states where user_id=v_goal.user_id for update;
    v_state:=coalesce(v_state,'{}'::jsonb);
    v_state:=jsonb_set(v_state,'{points}',to_jsonb(coalesce((v_state->>'points')::integer,0)+v_delta),true);
    v_state:=jsonb_set(v_state,'{history}',jsonb_build_array(jsonb_build_array('weekly','Meta semanal alcançada',0,'Bônus automático da semana','plus',v_delta,'weekly:'||v_goal.id||':'||v_total))||coalesce(v_state->'history','[]'::jsonb),true);
    update public.barber_states set state=v_state,updated_at=now() where user_id=v_goal.user_id;
    insert into public.app_notifications(user_id,type,title,message,metadata)
      values(v_goal.user_id,'weekly_goal','Meta semanal alcançada','Você conquistou +'||v_delta||' pontos na meta de '||v_goal.focus_key||'.',jsonb_build_object('view','dashboard'));
  end if;
  return jsonb_build_object('ok',true,'bonus',v_delta,'progress',v_progress,'total_bonus',v_total);
end $$;

grant execute on function public.ensure_current_weekly_challenges() to authenticated;
grant execute on function public.apply_weekly_challenge(bigint) to authenticated;
notify pgrst, 'reload schema';
