-- BarberXP v60 — entradas e estoque auditável de produtos

create table if not exists public.product_stock_entries (
  id bigint generated by default as identity primary key,
  product_id bigint not null references public.products(id) on delete cascade,
  quantity integer not null check (quantity > 0),
  note text,
  created_by uuid not null references public.profiles(id),
  created_at timestamptz not null default now()
);

create index if not exists product_stock_entries_product_idx
  on public.product_stock_entries(product_id,created_at desc);

alter table public.product_stock_entries enable row level security;

drop policy if exists product_stock_entries_owner_read on public.product_stock_entries;
create policy product_stock_entries_owner_read on public.product_stock_entries
for select to authenticated using (
  exists(select 1 from public.profiles p where p.id=auth.uid() and p.active=true and p.role='leader')
);

drop policy if exists product_stock_entries_owner_insert on public.product_stock_entries;
create policy product_stock_entries_owner_insert on public.product_stock_entries
for insert to authenticated with check (
  created_by=auth.uid() and exists(
    select 1 from public.profiles p where p.id=auth.uid() and p.active=true and p.role='leader'
  )
);

grant select,insert on public.product_stock_entries to authenticated;
grant usage,select on sequence public.product_stock_entries_id_seq to authenticated;

notify pgrst, 'reload schema';
